spring.datasource.url=jdbc:mysql://${DB_HOST}/springbackend?useSSL=false
spring.datasource.url=jdbc:mysql://${DB_HOST}/springbackend?useSSL=true&requireSSL=true&verifyServerCertificate=false&enabledTLSProtocols=TLSv1.2

# Read from env vars injected by ESO
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDB103Dialect