# -------- STAGE 1: Build --------

# Use an official Maven image with JDK 8 to build the application
FROM maven:3.9.9-eclipse-temurin-8 AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy only pom first (better caching)
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source
COPY src ./src

# Build jar
RUN mvn clean package -DskipTests


# -------- STAGE 2: Runtime --------

# Use a smaller JRE image for runtime
FROM eclipse-temurin:8-jre-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy only built jar from builder
COPY --from=builder /app/target/*.jar app.jar

# Expose port
EXPOSE 8080

# Run app
ENTRYPOINT ["java","-jar","app.jar"]